version: '3'

services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  nginx:
    image: nginx:1.19.6-alpine
    container_name: nginx
    restart: always
    depends_on:
      - php
      - mysql
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/sites:/etc/nginx/conf.d
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
      - ./prestashop:/var/www/prestashop
    networks:
      - prestashopNet
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  php:
    build: docker/php
    container_name: php
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./prestashop:/var/www/prestashop
      - ./docker/php/conf/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - prestashopNet

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - ./docker/mysql/dbData:/var/lib/mysql
    networks:
      - prestashopNet
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

networks:
  prestashopNet:
    driver: "bridge"
